이은철 - feature/ 카페 개설 기능
InfoShareCrew/Main pull request #31
Opened 2024-10-15 09:32 UTC by LEEEUNCHEOL96

#26 카페개설관련 기능 생성완료했습니다
- 카페 생성 수정 삭제 / 대분류,소분류 종속관계
- erd 기반으로 코드 작성했습니다

- 
![{1DB8A725-B650-42A4-B7DC-DBD89EDB14D7}](https://github.com/user-attachments/assets/ba687bc3-e903-4464-bdd7-d008f2d00fe8)

> 제가 만들면서 복잡한 구조로 만들어졌는데 맞는지 확인 부탁드립니다..!

2024-10-15 11:55 UTC, jinainkorea commented on src/main/java/com/infoShare/calog/domain/MinorCategory/MinorCategory.java
1. id 데이터 타입 Long => Short로 바꾸기
2. 컬럼 title => name으로 바꾸기

2024-10-15 11:56 UTC, jinainkorea commented on src/main/java/com/infoShare/calog/domain/MinorCategory/MinorCategoryService.java
카테고리 create할 때 관리자만 생성할 수 있어야 해서 관리자인지 확인해주는 코드 있으면 더 좋을 듯 합니다!

2024-10-15 11:56 UTC, jinainkorea commented on src/main/java/com/infoShare/calog/domain/MaiorCategory/MajorCategoryService.java
카테고리 create할 때 관리자만 할 수 있도록 해주면 더 좋습니다!

2024-10-15 11:57 UTC, jinainkorea commented on src/main/java/com/infoShare/calog/domain/MaiorCategory/MajorCategory.java
title => name으로 바꾸기

2024-10-15 12:00 UTC, jinainkorea commented on src/main/java/com/infoShare/calog/domain/Cafe/CafeController.java
카페 create할 때 만든 form, 파라미터로 넣어줬음 좋겠어요!
![image](https://github.com/user-attachments/assets/168c678e-990c-4da1-9c39-0c450d63bdc1)

2024-10-15 12:01 UTC, jinainkorea commented on src/main/java/com/infoShare/calog/domain/Cafe/CafeController.java
getMapping할 때는 그냥 넣어주고, postMapping할 때는 @Valid 붙여주기

2024-10-15 12:03 UTC, jinainkorea requested changes
잘하셨습니다! 일단 수정사항이 좀 있는데요, 
1. 카테고리 id 데이터형 Short로 바꾸기. Long까지 갈 필요는 없어요~
2. 카테고리 컬럼 이름 title에서 name으로 바꾸기. 나중에 헷갈릴 것 같아용
3. 카페 create할 때 GetMapping에는 form을 파라미터로 넣어주고 PostMapping에는 @Valid붙여서 넣어주기
4. (선택 사항) 카테고리들 create할 때 관리자만 할 수 있어야 하는데, 관리자인지 확인하고 아니면 에러 throw하는 거 있었으면 좋겠습니다!

2024-10-16 03:06 UTC, LEEEUNCHEOL96 commented
# 수정사항 완료 했습니다.

- [x] 카테고리 id 데이터형 Short로 바꾸기 .
- [x]  카테고리 컬럼 이름 title에서 name으로 바꾸기. 
- [x]  카페 create할 때 GetMapping에는 form을 파라미터로 넣어주고 PostMapping에는 @Valid붙여서 넣어주기

- [ ]  (선택 사항) 카테고리 create 시 관리자 판단 기능
 >  관리자 판단기능은 미구현 되었습니다

 # 추가 완료사항 
카페,대분류카테고리,소분류카테고리 수정,삭제 기능

2024-10-16 03:57 UTC, closed without merging